language: java
jdk: openjdk8
install: true
deploy:
    - provider: s3
      access_key_id: $AWS_ACCESS
      secret_access_key: $AWS_KEY
      bucket: 'codekillers'
      skip_cleanup: true
script:mvn site
